language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
env:
  global:
  - secure: XFtLYKpTUeADGybYz3LGH3foqPBaNDCmOD9Cp4Ktf71m8BXz1yFNQEniQnm312tSsr0kEqIVSFTCuQoqBlCocajqlQ6/k7epvN39tf0x6WWHyp4furuM/yZHKYBmDNE6yfPR6O2JD67i5/7OTccFCiPSeaNbN8DsUvvt+V9SvTs=
  - secure: SPYu75DWVg68GqPyomcxxfbH10fIPWDCkjrrnN3ooWzLyDXD0uwgD+XwBapkqFRVE2Zifs26L3e/phUeFuj6lw3RR37KqgC2Yh3HTcOy7TuTMNAskbUL7a0p8uh3bZq2SZmi5DkDTD38Oyq4Cr7fXBIw/ukabt8Si59MEjuYrns=
